export const header: string;
export const subheader: string;
export const title: string;
export const subtitle: string;
export const subtitleAlt: string;
export const base: string;
export const baseAlt: string;
export const light: string;
export const dark: string;
